version: '3.8'

services:
  db:
    image: mysql:5.7
    # restart: always
    environment:
      MYSQL_DATABASE: db_matterhorn_wp
      # MYSQL_USER: c3_db_diamond
      # MYSQL_PASSWORD: asdf34HB
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: example
  web:
    image: nginx:alpine
    ports:
      - "89:80"
    volumes:
      - ./docker/web/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./website_localhost:/var/www/html
  
  java:
    build:
      context: .
      dockerfile: Java.Dockerfile
    user: root
    volumes:
      - ./website_localhost/:/var/www/html
    command: bash -c "javac Hello.java && java Hello"
  openjdk:
    build:
      context: .
      dockerfile: Openjdk.Dockerfile
    user: root
    volumes:
      - ./website_localhost/:/usr/src/myapp
    # command: bash -c "javac Hello.java && java Hello"
    command: bash -c "cd package && javac Main.java && java Main"
  bitnami-java:
    image: bitnami/java:latest
    command: "java -jar package.jar"
    volumes:
      - ./website_localhost/:/app